Upgrade to Laravel 11.
hyn/multi-tenant pull request #1047
Opened 2024-05-11 16:16 UTC by mikebronner

2024-05-12 09:10 UTC, ArlonAntonius commented
@mikebronner Thank you for starting the effort on this, let us know if there's anything we can do to help update this package.

2024-12-04 11:20 UTC, chintan13 commented
Looking for upgrade to laravel 11, thank you!

2024-12-04 13:54 UTC, mikebronner commented
After testing this for several months now on my clients I have not encountered any issues. @ArlonAntonius marking this ready for review. Although I have not used the two file methods. Could use some help implementing those.

2024-12-04 14:03 UTC, ArlonAntonius commented
@mikebronner have you really been tesing it in production like this?
So simply CI is broken?

2024-12-04 14:08 UTC, mikebronner commented
Yes, correct, but with the caveat that we have not been using file uploads in our multi-tenant apps. I assume the CI issues are from Laravel 11 now requiring PHP 8.2+, but I am unable to see why the CI is failing (when I click on the link it asks me to log in).

2024-12-08 13:53 UTC, ArlonAntonius requested changes

2024-12-08 13:53 UTC, ArlonAntonius commented on src/Website/Directory.php
> +    }
@mikebronner Maybe the only thing that still needs to be added are these methods to make sure nobody's application actually fails. Other than that: I'm fine with merging this

2026-02-24 13:04 UTC, closed without merging