Change loadViews to prepend tenant location so customized views will have priority
hyn/multi-tenant pull request #159
Opened 2016-09-23 14:01 UTC by Deleugpn

As mentioned on issue #152, it seems like a good idea to assume whenever a tenant-view exists, it should override the default system-view (otherwise why make the tenant view at all?). 

The change here is to simply `prepend` the tenant-view location path instead of just appending it. That way, when finding a view file, Laravel Finder will automatically take the tenant-view first, thus allowing the tenant to have precedence.

I was not able to come up with a Test Code for this small change, unfortunately.

2016-09-29 07:04 UTC, luceos requested changes
What would be better is to get a new config parameter into the multi-tenant configuration file that allows anyone to append or prepend. As making prepend default, I think we should keep append default for now. What do you think @Deleugpn ?

2016-09-29 13:28 UTC, Deleugpn commented
To be honest, I see no reason why someone would have a tenant-specific view page and want it to default to the system-wide one. It makes the tenant-specific view useless. That said, I also don't think a config flag would hurt in any way, so I'm going to try and follow that reasoning.

2016-09-30 07:35 UTC, Luceos commented
Makes sense. If you can make the tenant overrule by default, it would be fine. Anyway I want things to be as flexible as possible.

2016-10-05 07:27 UTC, luceos approved these changes

2016-10-05 07:28 UTC, Luceos commented
@Deleugpn I have reconsidered your comment and it makes sense to stick to your logic for now. Thank you.

2016-10-05 07:28 UTC, merged

2016-10-05 20:09 UTC, Deleugpn commented
I'd like to apologize, the last couple of weeks have been crazy and I haven't cleared any spare time, so that's why I didn't work towards your suggestion for this.
Regardless, thanks for considering it, I believe it will be a good thing for the package.

2016-10-06 07:18 UTC, Luceos commented
@Deleugpn no need to apologize, this is how life and open source works :+1: