Disable SQL-user generation
hyn/multi-tenant pull request #334
Opened 2017-11-21 21:19 UTC by Thijmen

Since I do not  want to create a SQL-user, I decided to create a PR that disables the SQL-user generation.

If a user of the package disables the generation of the SQL-user, he/she needs to make sure that the sql-user on the 'tenant'-connection can access the tenant database.

What are your thoughts?

2017-11-21 22:02 UTC, bkintanar requested changes

2017-11-21 22:02 UTC, bkintanar commented on tests/unit-tests/Repositories/WebsiteRepositoryTest.php
> +        }
Can we remove else here by declaring `tableForUsers` before the `if` statement?

2017-11-22 08:18 UTC, luceos commented on assets/configs/tenancy.php
> +         * re-use existing credentials.
@Thijmen I've rewritten this comment. You mentioned it uses the tenant connection, but in fact it clones the system connection config, not the tenant one? If so it should read:

"re-use existing system connection credentials"

2017-12-04 14:25 UTC, luceos commented
@Thijmen we talked about creating DatabaseCredentialsGenerators where we will have one for separate databases, one database separate tables etc. These generators will have to share some information, eg do we need to create a database/username etc..

Closing this one.

2017-12-04 14:25 UTC, closed without merging